### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application 

### ISSUE THREAD

**Issue by yueyuep** [Mondego/oreo#3]
when i run the following command(w10(64)  python3.6(32) ):
$ python controller.py 1
there was an error :

D:\anaconda\envs\oero-master32\python.exe H:/oreo-master/clone-detector/controller.py
search will be carried out with 1 nodes
loading previous run state
H:\oreo-master\clone-detector\scriptinator_metadata.scc doesn't exist, creating one with state EXECUTE_1
previous run state 0
running new command H:\oreo-master\clone-detector\execute.sh 1
Traceback (most recent call last):
  File "H:/oreo-master/clone-detector/controller.py", line 231, in <module>
    controller.execute()
  File "H:/oreo-master/clone-detector/controller.py", line 58, in execute
    command_params, self.full_file_path("Log_execute_1.out"), self.full_file_path("Log_execute_1.err"))
  File "H:/oreo-master/clone-detector/controller.py", line 172, in run_command
    p = subprocess.Popen(cmd, stdout=fo, stderr=fe, universal_newlines=True)
  File "D:\anaconda\envs\oero-master32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "D:\anaconda\envs\oero-master32\lib\subprocess.py", line 992, in _execute_child
    startupinfo)
OSError: [WinError 193] %1  is not a valid Win32 application 。

Process finished with exit code 1

**Comment by saini** [comment]
It seems you are running Oreo on Windows. Please use Linux to run Oreo. We tested Oreo on Ubuntu.
